title: Saksham Gupta
description: Aspiring Biomedical Scientist
logo: assets/self_pic.jpg
social_links:
  - name: Gmail
    icon: ğŸ“§
    url: mailto:saksham.gupta.y19@gmail.com
  - name: LinkedIn
    icon: ğŸ”—
    url: https://www.linkedin.com/in/saksham-gupta-392a3a202/
  - name: GitHub
    icon: ğŸ™
    url: https://github.com/saksham132

remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme
