title: Saksham Gupta
description: Aspiring Biomedical Scientist
logo: assets/self_pic.jpg
ğŸ“§ [Gmail](mailto:saksham.gupta.y19@gmail.com)  
ğŸ”— [LinkedIn](https://www.linkedin.com/in/saksham-gupta-392a3a202/)  
ğŸ™ [GitHub](https://github.com/saksham132)  

remote_theme: pages-themes/minimal@v0.2.0
